# config/services.yaml
parameters:
  avatars_directory: "%kernel.project_dir%/public/uploads/avatars"
  your_upload_directory: "%kernel.project_dir%/public/assets/exploration/images"

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true
    autoconfigure: true

  Doctrine\Common\Annotations\AnnotationReader:
    class: Doctrine\Common\Annotations\AnnotationReader
    public: true

  annotation_reader:
    alias: Doctrine\Common\Annotations\AnnotationReader

  # makes classes in src/ available to be used as services
  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  # Explicitly configure LocationController
  App\Controller\front_office\assistance\LocationController:
    arguments:
      $foursquareApiKey: "%env(FOURSQUARE_API_KEY)%"
      $cache: "@cache.app"

  # Existing service definition
  App\Service\NotificationService:
    arguments:
      $twilioSid: "%env(TWILIO_ACCOUNT_SID)%"
      $twilioToken: "%env(TWILIO_AUTH_TOKEN)%"
      $whatsappNumber: "%env(TWILIO_WHATSAPP_NUMBER)%"
      $senderEmail: "cyrinegaaloul6@gmail.com"
